import json

def update_file(file_path, data):
    with open(file_path, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    if "trees" not in existing:
        existing["trees"] = {}

    for key, value in data.items():
        existing["trees"][key] = value

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(existing, f, ensure_ascii=False, indent=2)

fr_updates = {
    "title": "Arbres & Plantations",
    "subtitle": "Surveillance intelligente par vision par ordinateur",
    "agronomy_phyto_vision": "Agronomie & Phyto-Vision",
    "diagnostic_subtitle_full": "Diagnostic IA des cultures · Labess-7B · RAG · YOLO v8 — 5 modèles",
    "refresh": "Actualiser",
    "total_detections": "Détections Totales",
    "disease_alerts_7d": "Alertes Maladies 7j",
    "agronomy_scans": "Agronomie — Scans",
    "phyto_vision_scans": "Phyto-Vision — Scans",
    "avg_ai_confidence": "Confiance IA moy.",
    "agronomy": "Agronomie",
    "agronomy_desc": "Maladies Feuilles · Citronnier · Oranger — 3 modèles YOLO",
    "phyto_vision": "Phyto-Vision",
    "phyto_vision_desc": "Olivier · Insectes & Ravageurs — 2 modèles YOLO",
    "leaf_diseases": "Maladies des Feuilles",
    "lemon_diseases": "Maladies Citronnier",
    "orange_diseases": "Maladies Oranger",
    "olive_diseases": "Maladies de l'Olivier",
    "insects_pests": "Insectes & Ravageurs",
    "import_image": "Importer une image",
    "browse": "Parcourir",
    "detection_log": "Journal des Détections",
    "detection_log_desc": "Flux phyto-sanitaire temps réel",
    "live": "LIVE",
    "refresh_btn": "Rafraîchir",
    "analysis_history": "Historique des Analyses",
    "no_events": "Aucun évènement — lancez un scan.",
    "no_analysis": "Aucune analyse sauvegardée.",
    "analyzing": "ANALYSE EN COURS",
    "saved": "SAUVEGARDÉ",
    "analyze": "Analyser",
    "reset": "Reset",
    "no_anomaly": "Aucune anomalie",
    "new_analysis": "Nouvelle analyse",
    "ai_report": "Rapport IA",
    "reports": "Rapports IA",
    "generated_auto": "Généré automatiquement",
    "no_report": "Aucun rapport",
    "analyze_x_images": "Analysez des images pour générer un rapport automatique",
    "generating": "Génération…",
    "start": "Démarrer",
    "before_report": "avant rapport",
    "report_triggered": "Rapport déclenché!",
    "active": "actives",
    "session": "session",
    "healthy": "Sain",
    "alert": "Alerte",
    "critical": "Critique",
    "read_all": "Lire tout",
    "collapse": "Réduire",
    "delete_confirm": "Supprimer ce diagnostic ?"
}

en_updates = {
    "title": "Trees & Plantations",
    "subtitle": "Intelligent monitoring via computer vision",
    "agronomy_phyto_vision": "Agronomy & Phyto-Vision",
    "diagnostic_subtitle_full": "AI Crop Diagnostics · Labess-7B · RAG · YOLO v8 — 5 models",
    "refresh": "Refresh",
    "total_detections": "Total Detections",
    "disease_alerts_7d": "7-Day Disease Alerts",
    "agronomy_scans": "Agronomy — Scans",
    "phyto_vision_scans": "Phyto-Vision — Scans",
    "avg_ai_confidence": "Avg. AI Confidence",
    "agronomy": "Agronomy",
    "agronomy_desc": "Leaf Diseases · Lemon · Orange — 3 YOLO models",
    "phyto_vision": "Phyto-Vision",
    "phyto_vision_desc": "Olive · Insects & Pests — 2 YOLO models",
    "leaf_diseases": "Leaf Diseases",
    "lemon_diseases": "Lemon Diseases",
    "orange_diseases": "Orange Diseases",
    "olive_diseases": "Olive Diseases",
    "insects_pests": "Insects & Pests",
    "import_image": "Import an image",
    "browse": "Browse",
    "detection_log": "Detection Log",
    "detection_log_desc": "Real-time phyto-sanitary feed",
    "live": "LIVE",
    "refresh_btn": "Refresh",
    "analysis_history": "Analysis History",
    "no_events": "No events — run a scan.",
    "no_analysis": "No saved analyses.",
    "analyzing": "ANALYSIS IN PROGRESS",
    "saved": "SAVED",
    "analyze": "Analyze",
    "reset": "Reset",
    "no_anomaly": "No anomaly",
    "new_analysis": "New analysis",
    "ai_report": "AI Report",
    "reports": "AI Reports",
    "generated_auto": "Generated automatically",
    "no_report": "No report",
    "analyze_x_images": "Analyze images to generate an automatic report",
    "generating": "Generating…",
    "start": "Start",
    "before_report": "before report",
    "report_triggered": "Report triggered!",
    "active": "active",
    "session": "session",
    "healthy": "Healthy",
    "alert": "Alert",
    "critical": "Critical",
    "read_all": "Read all",
    "collapse": "Collapse",
    "delete_confirm": "Delete this diagnostic?"
}

ar_updates = {
    "title": "الأشجار والمزارع",
    "subtitle": "مراقبة ذكية عبر الرؤية الحاسوبية",
    "agronomy_phyto_vision": "الزراعة والرؤية النباتية",
    "diagnostic_subtitle_full": "تشخيص المحاصيل بالذكاء الاصطناعي · Labess-7B · RAG · YOLO v8 — 5 نماذج",
    "refresh": "تحديث",
    "total_detections": "إجمالي الاكتشافات",
    "disease_alerts_7d": "تنبيهات الأمراض 7 أيام",
    "agronomy_scans": "الزراعة — عمليات المسح",
    "phyto_vision_scans": "الرؤية النباتية — عمليات المسح",
    "avg_ai_confidence": "متوسط ثقة الذكاء",
    "agronomy": "الزراعة",
    "agronomy_desc": "أمراض الأوراق · الليمون · البرتقال — 3 نماذج YOLO",
    "phyto_vision": "الرؤية النباتية",
    "phyto_vision_desc": "الزيتون · الحشرات والآفات — 2 نماذج YOLO",
    "leaf_diseases": "أمراض الأوراق",
    "lemon_diseases": "أمراض الليمون",
    "orange_diseases": "أمراض البرتقال",
    "olive_diseases": "أمراض الزيتون",
    "insects_pests": "الحشرات والآفات",
    "import_image": "استيراد صورة",
    "browse": "تصفح",
    "detection_log": "سجل الاكتشافات",
    "detection_log_desc": "بث مباشر للصحة النباتية",
    "live": "مباشر",
    "refresh_btn": "تحديث",
    "analysis_history": "سجل التحليلات",
    "no_events": "لا يوجد أحداث — ابدأ الفحص.",
    "no_analysis": "لا يوجد تحليلات محفوظة.",
    "analyzing": "جاري التحليل",
    "saved": "تم الحفظ",
    "analyze": "تحليل",
    "reset": "إعادة تعيين",
    "no_anomaly": "لا يوجد خلل",
    "new_analysis": "تحليل جديد",
    "ai_report": "تقرير الذكاء الاصطناعي",
    "reports": "تقارير الذكاء الاصطناعي",
    "generated_auto": "تم إنشاؤه تلقائيًا",
    "no_report": "لا يوجد تقرير",
    "analyze_x_images": "قم بتحليل الصور لإنشاء تقرير تلقائي",
    "generating": "جاري الإنشاء…",
    "start": "ابدأ",
    "before_report": "قبل التقرير",
    "report_triggered": "تم تشغيل التقرير!",
    "active": "نشط",
    "session": "الجلسة",
    "healthy": "سليم",
    "alert": "تنبيه",
    "critical": "حرج",
    "read_all": "قراءة الكل",
    "collapse": "إخفاء",
    "delete_confirm": "حذف هذا التشخيص؟"
}

update_file('frontend/src/locales/fr.json', fr_updates)
update_file('frontend/src/locales/en.json', en_updates)
update_file('frontend/src/locales/ar.json', ar_updates)

print("Trees JSON updated.")
