[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*:
    ignore::DeprecationWarning:httpx.*:
    ignore::DeprecationWarning:jose.*:
    ignore::sqlalchemy.exc.MovedIn20Warning:
