import { useState, useEffect, useRef } from 'react';
import { agentAPI } from '../services/api';

// Per-species welcome messages in Derja
const WELCOME = {
  cow:       "أهلاً بيك يا فلاح! أنا خبيرك في تربية الأبقار. حمّل صورة أو اسألني.",
  sheep:     "أهلاً! أنا خبيرك في الغنم. كيفاش نقدر نعاونك اليوم؟",
  goat:      "أهلاً! أنا هنا باش نساعدك في تربية الماعز.",
  livestock: "أهلاً بيك! أنا خبيرك في المواشي. ما الذي تريد معرفته؟",
  bee:       "أهلاً يا نحّال! أنا خبيرك في النحل. اسألني عن روشك أو حمّل صورة.",
  poultry:   "أهلاً! أنا خبيرك في الدواجن. كيفاش نقدر نساعدك؟",
  rabbit:    "أهلاً! أنا خبيرك في الأرانب. ما هو مشكلتك اليوم؟",
  leaves:    "أهلاً يا فلاح! أنا خبيرك في أمراض النباتات. حمّل صورة أو اسألني عن زرعك.",
  olive:     "أهلاً! أنا خبيرك في زيتون تونس. صور زيتونتك وأنا نشخّص ليك.",
  insects:   "أهلاً! أنا خبيرك في مكافحة الحشرات. حمّل صورة الحشرة أو الضرر.",
  fire:      "⚠️ نظام الطوارئ نشيط. إذا كان في حريق، اتصل بالحماية المدنية 198 فوراً!",
  plant:     "أهلاً! أنا خبيرك في الزراعة. حمّل صورة المشكل أو اسألني.",
};

// Auto-generated question from detections
function buildAutoQuery(detections, species) {
  if (!detections || detections.length === 0) return null;

  const counts = {};
  detections.forEach(d => {
    const label = d.label || d.object_class || 'unknown';
    counts[label] = (counts[label] || 0) + 1;
  });

  const summary = Object.entries(counts)
    .map(([label, count]) => `${count} ${label.replace(/_/g, ' ')}`)
    .join('، ');

  const categoryMap = {
    bee:       `شفت في الصورة: ${summary}. شنوا هو التشخيص وكيفاش نعالج؟`,
    cow:       `الكاميرا كشفت: ${summary}. شنوا هو المشكل وكيفاش نتصرف؟`,
    livestock: `الكاميرا كشفت: ${summary}. ما هو تشخيصك وما هي خطوات العلاج؟`,
    sheep:     `شفت في الصورة: ${summary}. شنوا راك تشوف وكيفاش نعالج؟`,
    goat:      `الكاميرا كشفت: ${summary}. ما هو تشخيصك؟`,
    poultry:   `الكاميرا شافت: ${summary}. هل هو خطير؟ كيفاش نتدخل فوراً؟`,
    rabbit:    `شفت: ${summary}. شنوا المشكل وما هو العلاج؟`,
    leaves:    `الكاميرا كشفت على زرعتي: ${summary}. شنوا هو المرض وكيفاش نعالج؟`,
    olive:     `شفت في زيتوني: ${summary}. شنوا هو هذا المرض وكيفاش نرشّ؟`,
    insects:   `الكاميرا شافت في حقلي: ${summary}. هاي الحشرات خطيرة؟ كيفاش نقاومهم؟`,
    fire:      `⚠️ الكاميرا كشفت: ${summary} — ما هو الإجراء الطارئ الفوري؟`,
    plant:     `الكاميرا كشفت: ${summary}. شنوا التشخيص والعلاج؟`,
  };

  return categoryMap[species] || `الكاميرا كشفت: ${summary}. شنوا تشخيصك وكيفاش نتصرف؟`;
}

export const useExpertAgent = (species = 'cow') => {
  const welcome = WELCOME[species] || "أهلاً! كيفاش نقدر نساعدك اليوم؟";
  const [messages, setMessages] = useState([
    { role: 'assistant', text: welcome }
  ]);
  const [isTyping,    setIsTyping]    = useState(false);
  const [pendingDets, setPendingDets] = useState(null);
  const scrollRef = useRef(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isTyping]);

  // Called when ExpertAssistant receives detections from AIScanner
  const analyzeDetections = async (detections, category) => {
    const sp = category || species;
    const autoQuery = buildAutoQuery(detections, sp);
    if (!autoQuery) return;

    const userMsg = {
      role: 'user',
      text: autoQuery,
      isAutoGenerated: true,
      detectionCount: detections.length,
    };
    setMessages(prev => [...prev, userMsg]);
    setIsTyping(true);

    try {
      const res = await agentAPI.analyze(autoQuery, sp, detections);
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: res.data.response_derja,
        intent: res.data.intent,
        sources: res.data.sources,
        cvContextUsed: res.data.cv_detections_used,
      }]);
    } catch {
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: "عذراً، صار مشكل في الاتصال. حاول مرة أخرى.",
      }]);
    } finally {
      setIsTyping(false);
    }
  };

  const sendMessage = async (text, detections = null) => {
    if (!text.trim()) return;
    setMessages(prev => [...prev, { role: 'user', text }]);
    setIsTyping(true);

    try {
      let res;
      if (detections && detections.length > 0) {
        res = await agentAPI.analyze(text, species, detections);
      } else {
        res = await agentAPI.chat(text, species);
      }
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: res.data.response_derja,
        sources: res.data.sources,
        cvContextUsed: res.data.cv_detections_used,
      }]);
    } catch {
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: "عذراً، صار مشكل في الاتصال.",
      }]);
    } finally {
      setIsTyping(false);
    }
  };

  const clearHistory = () => {
    setMessages([{ role: 'assistant', text: welcome }]);
  };

  return {
    messages,
    isTyping,
    sendMessage,
    analyzeDetections,
    clearHistory,
    scrollRef,
  };
};
