"""initial_schema

Revision ID: 022cb45ad724
Revises: 
Create Date: 2026-05-20 02:39:02.286337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022cb45ad724'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('telemetry_schema', sa.JSON(), nullable=True),
    sa.Column('cv_classes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species')
    )
    op.create_index(op.f('ix_animal_types_id'), 'animal_types', ['id'], unique=False)
    op.create_table('bee_apiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('flower_type', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_apiaries_id'), 'bee_apiaries', ['id'], unique=False)
    op.create_table('bee_global_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sirop', sa.Float(), nullable=True),
    sa.Column('pate', sa.Float(), nullable=True),
    sa.Column('traitement', sa.Integer(), nullable=True),
    sa.Column('cadres', sa.Integer(), nullable=True),
    sa.Column('hausse', sa.Integer(), nullable=True),
    sa.Column('equipement', sa.Integer(), nullable=True),
    sa.Column('sirop_min', sa.Float(), nullable=True),
    sa.Column('pate_min', sa.Float(), nullable=True),
    sa.Column('traitement_min', sa.Integer(), nullable=True),
    sa.Column('cadres_min', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_global_stock_id'), 'bee_global_stock', ['id'], unique=False)
    op.create_table('bee_stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.String(length=20), nullable=False),
    sa.Column('sirop', sa.Float(), nullable=True),
    sa.Column('pate', sa.Float(), nullable=True),
    sa.Column('traitement', sa.Float(), nullable=True),
    sa.Column('cadres', sa.Integer(), nullable=True),
    sa.Column('hausse', sa.Integer(), nullable=True),
    sa.Column('equipement', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bee_stock_date', 'bee_stock_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_bee_stock_logs_id'), 'bee_stock_logs', ['id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('veterinarians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinarians_id'), 'veterinarians', ['id'], unique=False)
    op.create_table('warehouse_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_categories_id'), 'warehouse_categories', ['id'], unique=False)
    op.create_table('bee_hives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiary_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('honey_level', sa.Float(), nullable=True),
    sa.Column('force_level', sa.Float(), nullable=True),
    sa.Column('hive_type', sa.String(length=50), nullable=True),
    sa.Column('queen_year', sa.Integer(), nullable=True),
    sa.Column('has_queen', sa.Boolean(), nullable=True),
    sa.Column('queen_count', sa.Integer(), nullable=True),
    sa.Column('last_visit_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['bee_apiaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_bee_hives_id'), 'bee_hives', ['id'], unique=False)
    op.create_table('diagnostic_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('detections', sa.JSON(), nullable=True),
    sa.Column('chat_log', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diag_history_user_time', 'diagnostic_history', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_diagnostic_history_id'), 'diagnostic_history', ['id'], unique=False)
    op.create_index(op.f('ix_diagnostic_history_timestamp'), 'diagnostic_history', ['timestamp'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_area_ha', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.create_table('warehouse_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_fr', sa.String(length=150), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['warehouse_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouse_item_cat', 'warehouse_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_warehouse_items_id'), 'warehouse_items', ['id'], unique=False)
    op.create_table('animal_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_index('ix_animal_units_farm_type', 'animal_units', ['farm_id', 'type_id'], unique=False)
    op.create_index(op.f('ix_animal_units_id'), 'animal_units', ['id'], unique=False)
    op.create_table('bee_hive_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('sirop', sa.Float(), nullable=True),
    sa.Column('pate', sa.Float(), nullable=True),
    sa.Column('traitement', sa.Integer(), nullable=True),
    sa.Column('cadres', sa.Integer(), nullable=True),
    sa.Column('sirop_min', sa.Float(), nullable=True),
    sa.Column('pate_min', sa.Float(), nullable=True),
    sa.Column('traitement_min', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['bee_hives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hive_id')
    )
    op.create_index(op.f('ix_bee_hive_stocks_id'), 'bee_hive_stocks', ['id'], unique=False)
    op.create_table('bee_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('apiary_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('predicted_sirop', sa.Float(), nullable=True),
    sa.Column('predicted_pate', sa.Float(), nullable=True),
    sa.Column('predicted_traitement', sa.Integer(), nullable=True),
    sa.Column('predicted_cadres', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['bee_apiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hive_id'], ['bee_hives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bee_plan_hive_date', 'bee_planning', ['hive_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_bee_planning_id'), 'bee_planning', ['id'], unique=False)
    op.create_table('bee_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('apiary_id', sa.Integer(), nullable=True),
    sa.Column('flower_type', sa.String(length=100), nullable=True),
    sa.Column('production_date', sa.String(length=20), nullable=False),
    sa.Column('honey_kg', sa.Float(), nullable=True),
    sa.Column('pollen_kg', sa.Float(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['bee_apiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hive_id'], ['bee_hives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bee_prod_apiary_date', 'bee_productions', ['apiary_id', 'production_date'], unique=False)
    op.create_index('ix_bee_prod_hive_date', 'bee_productions', ['hive_id', 'production_date'], unique=False)
    op.create_index(op.f('ix_bee_productions_id'), 'bee_productions', ['id'], unique=False)
    op.create_table('bee_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('apiary_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.String(length=20), nullable=False),
    sa.Column('gps_coords', sa.String(length=100), nullable=True),
    sa.Column('health_state', sa.String(length=20), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('force_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('honey_level', sa.String(length=20), nullable=True),
    sa.Column('needs_sirop', sa.Float(), nullable=True),
    sa.Column('needs_pate', sa.Float(), nullable=True),
    sa.Column('needs_traitement', sa.Float(), nullable=True),
    sa.Column('harvest_kg', sa.Float(), nullable=True),
    sa.Column('pollen_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['bee_apiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hive_id'], ['bee_hives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bee_visits_apiary_date', 'bee_visits', ['apiary_id', 'visit_date'], unique=False)
    op.create_index(op.f('ix_bee_visits_id'), 'bee_visits', ['id'], unique=False)
    op.create_table('farm_finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_finances_id'), 'farm_finances', ['id'], unique=False)
    op.create_index(op.f('ix_farm_finances_timestamp'), 'farm_finances', ['timestamp'], unique=False)
    op.create_table('farm_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'owner_id', name='uq_farm_owner')
    )
    op.create_index(op.f('ix_farm_owners_id'), 'farm_owners', ['id'], unique=False)
    op.create_table('poultry_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('batch_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_batches_id'), 'poultry_batches', ['id'], unique=False)
    op.create_table('poultry_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_inventory_id'), 'poultry_inventory', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('animal_type_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settings_farm_type_key', 'settings', ['farm_id', 'animal_type_id', 'key'], unique=False)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('warehouse_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['warehouse_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouse_alert_resolved', 'warehouse_alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_warehouse_alerts_created_at'), 'warehouse_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouse_alerts_id'), 'warehouse_alerts', ['id'], unique=False)
    op.create_table('worker_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('pin_code', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_assignments_id'), 'worker_assignments', ['id'], unique=False)
    op.create_table('worker_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_b64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_reports_id'), 'worker_reports', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_resolved', 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index('ix_alerts_unit_severity', 'alerts', ['unit_id', 'severity'], unique=False)
    op.create_table('animal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_animal_logs_animal_time', 'animal_logs', ['animal_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_animal_logs_id'), 'animal_logs', ['id'], unique=False)
    op.create_index(op.f('ix_animal_logs_timestamp'), 'animal_logs', ['timestamp'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('isolation_score', sa.Float(), nullable=True),
    sa.Column('rules_triggered', sa.JSON(), nullable=True),
    sa.Column('feature_contributions', sa.JSON(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_index('ix_anomalies_unit_time', 'anomalies', ['unit_id', 'timestamp'], unique=False)
    op.create_table('bee_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=True),
    sa.Column('apiary_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_planned', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['bee_apiaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hive_id'], ['bee_hives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['bee_visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bee_expense_apiary_date', 'bee_expenses', ['apiary_id', 'expense_date'], unique=False)
    op.create_index('ix_bee_expense_hive_date', 'bee_expenses', ['hive_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_bee_expenses_id'), 'bee_expenses', ['id'], unique=False)
    op.create_table('bee_planning_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_id'], ['bee_planning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bee_planning_tasks_id'), 'bee_planning_tasks', ['id'], unique=False)
    op.create_table('cv_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('object_class', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('frame_metadata', sa.JSON(), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_events_id'), 'cv_events', ['id'], unique=False)
    op.create_index(op.f('ix_cv_events_timestamp'), 'cv_events', ['timestamp'], unique=False)
    op.create_index('ix_cv_events_unit_time', 'cv_events', ['unit_id', 'timestamp'], unique=False)
    op.create_table('poultry_egg_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_eggs', sa.Integer(), nullable=False),
    sa.Column('broken_eggs', sa.Integer(), nullable=True),
    sa.Column('grade_a_count', sa.Integer(), nullable=True),
    sa.Column('grade_b_count', sa.Integer(), nullable=True),
    sa.Column('production_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_egg_logs_id'), 'poultry_egg_logs', ['id'], unique=False)
    op.create_table('poultry_feed_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('feed_type', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('average_weight_g', sa.Float(), nullable=True),
    sa.Column('fcr_calculated', sa.Float(), nullable=True),
    sa.Column('cost_per_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_feed_logs_id'), 'poultry_feed_logs', ['id'], unique=False)
    op.create_table('poultry_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('deaths_today', sa.Integer(), nullable=True),
    sa.Column('medicine_used', sa.String(length=200), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_health_logs_id'), 'poultry_health_logs', ['id'], unique=False)
    op.create_table('poultry_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_sales_id'), 'poultry_sales', ['id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('sensor_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_id'), 'telemetry_records', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    op.create_index('ix_telemetry_unit_time', 'telemetry_records', ['unit_id', 'timestamp'], unique=False)
    op.create_table('worker_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_tasks_id'), 'worker_tasks', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('probable_cause', sa.Text(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_actioned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['animal_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index('ix_recommendations_unit', 'recommendations', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_unit', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_worker_tasks_id'), table_name='worker_tasks')
    op.drop_table('worker_tasks')
    op.drop_index('ix_telemetry_unit_time', table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_id'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_poultry_sales_id'), table_name='poultry_sales')
    op.drop_table('poultry_sales')
    op.drop_index(op.f('ix_poultry_health_logs_id'), table_name='poultry_health_logs')
    op.drop_table('poultry_health_logs')
    op.drop_index(op.f('ix_poultry_feed_logs_id'), table_name='poultry_feed_logs')
    op.drop_table('poultry_feed_logs')
    op.drop_index(op.f('ix_poultry_egg_logs_id'), table_name='poultry_egg_logs')
    op.drop_table('poultry_egg_logs')
    op.drop_index('ix_cv_events_unit_time', table_name='cv_events')
    op.drop_index(op.f('ix_cv_events_timestamp'), table_name='cv_events')
    op.drop_index(op.f('ix_cv_events_id'), table_name='cv_events')
    op.drop_table('cv_events')
    op.drop_index(op.f('ix_bee_planning_tasks_id'), table_name='bee_planning_tasks')
    op.drop_table('bee_planning_tasks')
    op.drop_index(op.f('ix_bee_expenses_id'), table_name='bee_expenses')
    op.drop_index('ix_bee_expense_hive_date', table_name='bee_expenses')
    op.drop_index('ix_bee_expense_apiary_date', table_name='bee_expenses')
    op.drop_table('bee_expenses')
    op.drop_index('ix_anomalies_unit_time', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_animal_logs_timestamp'), table_name='animal_logs')
    op.drop_index(op.f('ix_animal_logs_id'), table_name='animal_logs')
    op.drop_index('ix_animal_logs_animal_time', table_name='animal_logs')
    op.drop_table('animal_logs')
    op.drop_index('ix_alerts_unit_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index('ix_alerts_resolved', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_worker_reports_id'), table_name='worker_reports')
    op.drop_table('worker_reports')
    op.drop_index(op.f('ix_worker_assignments_id'), table_name='worker_assignments')
    op.drop_table('worker_assignments')
    op.drop_index(op.f('ix_warehouse_alerts_id'), table_name='warehouse_alerts')
    op.drop_index(op.f('ix_warehouse_alerts_created_at'), table_name='warehouse_alerts')
    op.drop_index('ix_warehouse_alert_resolved', table_name='warehouse_alerts')
    op.drop_table('warehouse_alerts')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index('ix_settings_farm_type_key', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_poultry_inventory_id'), table_name='poultry_inventory')
    op.drop_table('poultry_inventory')
    op.drop_index(op.f('ix_poultry_batches_id'), table_name='poultry_batches')
    op.drop_table('poultry_batches')
    op.drop_index(op.f('ix_farm_owners_id'), table_name='farm_owners')
    op.drop_table('farm_owners')
    op.drop_index(op.f('ix_farm_finances_timestamp'), table_name='farm_finances')
    op.drop_index(op.f('ix_farm_finances_id'), table_name='farm_finances')
    op.drop_table('farm_finances')
    op.drop_index(op.f('ix_bee_visits_id'), table_name='bee_visits')
    op.drop_index('ix_bee_visits_apiary_date', table_name='bee_visits')
    op.drop_table('bee_visits')
    op.drop_index(op.f('ix_bee_productions_id'), table_name='bee_productions')
    op.drop_index('ix_bee_prod_hive_date', table_name='bee_productions')
    op.drop_index('ix_bee_prod_apiary_date', table_name='bee_productions')
    op.drop_table('bee_productions')
    op.drop_index(op.f('ix_bee_planning_id'), table_name='bee_planning')
    op.drop_index('ix_bee_plan_hive_date', table_name='bee_planning')
    op.drop_table('bee_planning')
    op.drop_index(op.f('ix_bee_hive_stocks_id'), table_name='bee_hive_stocks')
    op.drop_table('bee_hive_stocks')
    op.drop_index(op.f('ix_animal_units_id'), table_name='animal_units')
    op.drop_index('ix_animal_units_farm_type', table_name='animal_units')
    op.drop_table('animal_units')
    op.drop_index(op.f('ix_warehouse_items_id'), table_name='warehouse_items')
    op.drop_index('ix_warehouse_item_cat', table_name='warehouse_items')
    op.drop_table('warehouse_items')
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_diagnostic_history_timestamp'), table_name='diagnostic_history')
    op.drop_index(op.f('ix_diagnostic_history_id'), table_name='diagnostic_history')
    op.drop_index('ix_diag_history_user_time', table_name='diagnostic_history')
    op.drop_table('diagnostic_history')
    op.drop_index(op.f('ix_bee_hives_id'), table_name='bee_hives')
    op.drop_table('bee_hives')
    op.drop_index(op.f('ix_warehouse_categories_id'), table_name='warehouse_categories')
    op.drop_table('warehouse_categories')
    op.drop_index(op.f('ix_veterinarians_id'), table_name='veterinarians')
    op.drop_table('veterinarians')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_bee_stock_logs_id'), table_name='bee_stock_logs')
    op.drop_index('ix_bee_stock_date', table_name='bee_stock_logs')
    op.drop_table('bee_stock_logs')
    op.drop_index(op.f('ix_bee_global_stock_id'), table_name='bee_global_stock')
    op.drop_table('bee_global_stock')
    op.drop_index(op.f('ix_bee_apiaries_id'), table_name='bee_apiaries')
    op.drop_table('bee_apiaries')
    op.drop_index(op.f('ix_animal_types_id'), table_name='animal_types')
    op.drop_table('animal_types')
    # ### end Alembic commands ###
